### ISSUE TITLE
Update supported versions

### ISSUE THREAD

**Issue by Malinskiy** [plezentek/bazel-sqlc#10]
Hi, thanks for awesome project!

Just wanted to ask if the project could be updated with the latest sqlc?

The max supported version is [1.6.0](https://github.com/plezentek/rules_sqlc/blob/main/sqlc/private/sqlc_versions.bzl#L20). Would be nice to add the definitions for https://github.com/kyleconroy/sqlc/releases/tag/v1.14.0.

Maybe it would be nice if the configuration supported user-specified versions as well.

Thanks!

**Comment by douglas-plezentek** [comment]
Sure.  I'm taking a look at this today.

**Comment by douglas-plezentek** [comment]
Done, and released for versions up to 1.14.0.

Adding the ability to specify a url and checksum are possible, but would take some more time.  I'm also happy to accept a PR if you'd like to add that in.

**Comment by Malinskiy** [comment]
@douglas-plezentek thanks a lot for this :partying_face: 
I'll see if I can create a PR with support for custom distributions: still pretty new to bazel
