### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by adamj-codethink** [plezentek/bazel-sqlc#2]
Thanks for contributing these rules.

I think it would make sense to discuss feedback from other vendors for SQLC.

What issues need solving?

**Comment by dmayle** [comment]
As to the documentation request, one the rules land later this week, there is a second pull request that will come from the stardoc branch which provides up-to-date documentation for the rules and providers.

As to other vendors, I'm happy to respond to feedback once I receive some.
